<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/html" class="x-border-box x-strict">
    <head>
        <!-- End Google Tag Manager -->
        <meta http-equiv="X-UA-Compatible" content="chrome=1">
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
       <link rel="stylesheet" type="text/css" href="https://cdn1.alegra.com/long-term/compressed/ext-theme-gray-all2.css">
       <link type="image/x-icon" rel="shortcut icon" href="https://cdn1.alegra.com/images/favicon.ico">
      <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.teal-green.min.css">
         <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
         <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <!-- <link href = "https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-triton/resources/theme-triton-all.css" rel = "stylesheet" />-->
         <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
         <script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/Big.min.js"></script>
       <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/extjs/4.2.1/ext-all.min.js"></script>      
        <script type="text/javascript" src="/app.js"></script>
        <script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/ext-lang-es.js"></script>
    
      
        <title>Contactos</title>
        <meta id="wwi3bdi87sg87gi3av8bc8sgeyvru2y3">
        
        <style media="print" class="jx_ui_StyleSheet" __jx__id="___$_2" type="text/css">.zopim { display: none !important }</style>
    </head>
    <body id="contact-index" class="x-body x-webkit x-chrome">
        <div class="zopim" __jx__id="___$_61 ___$_61" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; border: 0px; background: transparent; overflow: hidden; position: fixed; z-index: 16000002; width: 187px; height: 30px; right: 10px; bottom: 0px; display: none;">
        <iframe frameborder="0" src="about:blank" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 100%; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;"></iframe></div>
        <div class="zopim" __jx__id="___$_4 ___$_4" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; border: 0px; background: transparent; overflow: hidden; position: fixed; z-index: 16000001; right: 10px; bottom: 0px; border-top-left-radius: 5px; border-top-right-radius: 5px; display: none; width: 290px; height: 400px; box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 3px 2px;">
        <iframe frameborder="0" src="about:blank" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 100%; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;"></iframe></div>
        <!-- Google Tag Manager (noscript) -->
        <noscript>&lt;iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KQG46G"
            height="0" width="0" style="display:none;visibility:hidden"&gt;&lt;/iframe&gt;
        </noscript>
        <!-- End Google Tag Manager (noscript) -->
        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
         <header class="mdl-layout__header">
            <div class="mdl-layout__header-row"  style="background-color: white">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-left">
                    <label class="mdl-button mdl-js-button mdl-button--icon" for="fixed-header-drawer-exp">
                     <i class="material-icons"style="color: #00BFA5">search</i>
                    </label>
                        <div class="mdl-textfield__expandable-holder">
                         <input class="mdl-textfield__input" type="text" placeholder="buscar..." name="sample" id="fixed-header-drawer-exp" style="border-color: #00BFA5">
                        </div>
                </div>
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation -->
                <nav class="mdl-navigation">
                    <i class="material-icons" style="color: grey">help</i><a class="mdl-navigation__link" style="color:grey" href="#">ayuda</a>
                    <i class="material-icons" style="color: grey">mail</i><a class="mdl-navigation__link"  style="color:grey" href="#">Soporte</a>
                    <i class="material-icons" style="color: grey">person</i><a class="mdl-navigation__link" style="color:grey" href="#">jose120293@gmail.com</a>
                 </nav>
            </div>
         </header>
            <div class="mdl-layout__drawer"  style="background-color:#00BFA5"> 
                 <div class="mdl-layout-title"  style="background-color:white">
                 <div class="logo" style="float:left; margin-top: 2px;margin-left:-10px; margin-bottom: 1px;">
                        <img src="https://cdn1.alegra.com/images/logo_alegra.png" style="width: 178px">
                    </div></div>
                    <nav class="mdl-navigation" style="background-color:#00BFA5" >
                    <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color: white">home</i>    INICIO</span></a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">trending_up</i>  INGRESOS</span></a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">trending_down</i>  GASTOS</span></a>
                     <a class="mdl-navigation__link is-active" href="" style="background-color: white"><span style="color:#00BFA5"><i class="material-icons" style="color:#00BFA5">group</i> CONTACTOS</span>                     </a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">domain</i>  INVENTARIOS</span></a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">store_mall_directory</i>  BANCOS</span></a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">device_hub</i> CATEGORIAS</span></a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">multiline_chart</i>  REPORTES</span></a>
                     <a class="mdl-navigation__link" href="#" style="background-color: #00BFA5"><span style="color:white"><i class="material-icons" style="color:white">brightness_low</i> CONFIGURACIONES</span></a>  
                    </nav>
            </div>
        <main class="mdl-layout__content">
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--1-col mdl-cell--8-col-tablet">
                <div class="center" style="margin-top:14px; margin-left:25px">
                <i class="material-icons" style="font-size: 48px; color: rgba(22, 112, 100, 0.719)">contacts</i>
                </div>
                </div>
                <div class="mdl-cell mdl-cell--7-col mdl-cell--8-col-tablet">
                    <h3><span style="color:rgba(22, 112, 100, 0.719)">Contactos</span></h3>
                </div>
                    <div class="mdl-cell mdl-cell--4-col mdl-cell--8-col-tablet">
                    <button class="mdl-button mdl-button--raised" style="margin-top:24px"><span style="color:rgba(22, 112, 100, 0.719)"><i class="material-icons" style="color:rgba(22, 112, 100, 0.719)">arrow_upward</i> Importar</span></button>
                    <button class="mdl-button mdl-button--raised" style="margin-top:24px"><span style="color:rgba(22, 112, 100, 0.719)"><i class="material-icons" style="color:rgba(22, 112, 100, 0.719)">arrow_downward</i> Expotar</span></button>
                    </div>
            </div>
            <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--12-col mdl-cell--8-col-tablet">
                        <div id="notification-wrapper"></div>
                        <div id="alegra_content">
                            <?php  echo $this->layout()->content ?>
                        </div>
                    </div>
            </div>
            <footer class="mdl-mega-footer" style="background-color:#00BFA5">
                 <div class="mdl-mega-footer__middle-section">

                <div class="mdl-mega-footer__drop-down-section">
                 <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
                <h1 class="mdl-mega-footer__heading">Imformacion</h1>
                <ul class="mdl-mega-footer__link-list">
                <li style="color :white"><a href="#">Sobre nosotros</a></li>
                <li style="color :white"><a href="#">Terminos</a></li>
                <li style="color :white"><a href="#">Patrocinantes</a></li>
                <li style="color :white"><a href="#">Actualizaciones</a></li>
                </ul>
            </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Detalles</h1>
      <ul class="mdl-mega-footer__link-list">
        <li style="color :white"><a href="#">Aspectos</a></li>
        <li style="color :white"><a href="#">Herramientas</a></li>
        <li style="color :white"><a href="#">Recursos</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Tecnologia</h1>
      <ul class="mdl-mega-footer__link-list">
        <li style="color :white"><a href="#">Con que trabajamos  </a></li>
        <li style="color :white"><a href="#">Nuestros Productos</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">FAQ</h1>
      <ul class="mdl-mega-footer__link-list">
        <li style="color :white"><a href="#">Preguntas Frecuentes</a></li>
        <li style="color :white"><a href="#">Respuestas</a></li>
        <li style="color :white"><a href="#">Contactanos</a></li>
      </ul>
    </div>

  </div>

  <div class="mdl-mega-footer__bottom-section">
    <div class="mdl-logo">Ven con Nosotros y Alegra tu negocio</div>
    <ul class="mdl-mega-footer__link-list">
      <li style="color :white"><a href="#">Ayuda</a></li>
      <li style="color :white"><a href="#">Privacy & Terms</a></li>
    </ul>
  </div>

</footer>

        </main>
        </div>     
        <div style="display: none; visibility: hidden;">
            <noscript></noscript>
        </div>
   
    </body>
</html>